"""Language codes shared by dictionary build scripts."""

# Bergamot UI codes to English Wiktionary / Kaikki language names.
KAIKKI_NAMES = {
    "bg": "Bulgarian",
    "ca": "Catalan",
    "cs": "Czech",
    "da": "Danish",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "es": "Spanish",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "hr": "Croatian",
    "hu": "Hungarian",
    "id": "Indonesian",
    "it": "Italian",
    "nb": "Norwegian Bokmål",
    "nl": "Dutch",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sv": "Swedish",
    "tr": "Turkish",
	"uk": "Ukrainian",
	"vi": "Vietnamese",
	"zh": "Chinese",
	"ja": "Japanese",
}

# Bergamot codes to FreeDict ISO 639-3 style pair codes.
FREEDICT_CODES = {
    "bg": "bul",
    "ca": "cat",
    "cs": "ces",
    "da": "dan",
    "de": "deu",
    "el": "ell",
    "en": "eng",
    "es": "spa",
    "et": "est",
    "fi": "fin",
    "fr": "fra",
    "hr": "hrv",
    "hu": "hun",
    "id": "ind",
    "it": "ita",
    "nb": "nob",
    "nl": "nld",
    "pl": "pol",
    "pt": "por",
    "ro": "ron",
    "ru": "rus",
    "sk": "slk",
    "sl": "slv",
    "sv": "swe",
    "tr": "tur",
	"uk": "ukr",
	"vi": "vie",
	"zh": "zho",
	"ja": "jpn",
}

ALL_LANGS = sorted(KAIKKI_NAMES.keys())
